#!/usr/bin/env bash
set -e

rm -rf build

mkdir -p build/{debug,debug_clang,profile,release,san}

cd build/debug && cmake -GNinja ../.. -DCMAKE_BUILD_TYPE=Debug -DUSE_CLANG_TIDY=TRUE
cd ../profile && cmake -GNinja ../.. -DCMAKE_BUILD_TYPE=RelWithDebInfo -DPROFILE_BUILD=TRUE
cd ../release && cmake -GNinja ../.. -DCMAKE_BUILD_TYPE=Release
cd ../san && cmake -GNinja ../.. -DCMAKE_BUILD_TYPE=Debug -DSANITIZE=TRUE -DUSE_CLANG_TIDY=TRUE

if command -v clang &> /dev/null; then
    cd ../debug_clang && cmake -GNinja ../.. -DCMAKE_BUILD_TYPE=Debug -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang
fi
