#!/usr/bin/env bash
set -e

rm -rf build

if command -v nix > /dev/null; then
    # Nix sets AR=ar, which breaks LTO.
    AR=
fi

meson build/debug --buildtype=debug -Db_coverage=true $@
if command -v clang &> /dev/null; then
   CC=clang CXX=clang++ meson build/debug_clang --buildtype=debug -Db_coverage=true $@
   CC=clang CXX=clang++ meson build/release_clang --buildtype=release -Db_lto=true $@
fi
meson build/san --buildtype=debug -Db_sanitize=address,undefined $@
meson build/debugopt --buildtype=debugoptimized -Db_lto=true $@
meson build/profile --buildtype=debugoptimized -Db_ndebug=true -Dprofile=true $@
meson build/release --buildtype=release -Db_lto=true $@
