#!/bin/sh
set -e

BASE=$(dirname $(readlink -f "$0"))

rm -rf build

for CC in gcc clang cl; do
    if ! command -v $CC > /dev/null 2>&1; then
       continue
    fi

    case $CC in
        gcc) CXX=g++ ;;
        clang) CXX=clang++ ;;
        cl) CXX=cl ;;
    esac

    meson setup build/$CC/debug --buildtype=debug -Db_coverage=true -Db_sanitize=address,undefined $@
    meson setup build/$CC/release --buildtype=release -Db_lto=true $@
    meson setup build/$CC/profile --buildtype=debugoptimized -Db_ndebug=true -Db_lto=true -Dprofile=true
done
