function(target_disable_exceptions target)
  include(AddFlags)

  if (CMAKE_CXX_COMPILER_ID STREQUAL "MSVC")
    target_add_flag_cxx(${target} EHs-c- FALSE FALSE)
    target_compile_definitions(${target} PRIVATE _HAS_EXCEPTIONS=0)
  elseif (CMAKE_CXX_COMPILER_ID STREQUAL "GNU" OR CMAKE_CXX_COMPILER_ID MATCHES "Clang$" OR CMAKE_CXX_COMPILER_ID STREQUAL "Intel")
    target_add_flag_cxx(${target} fno-exceptions FALSE FALSE)
  else()
    message(WARNING "Unknown compiler: Cannot disable exceptions.")
  endif()
endfunction()
