option(SANITIZE "Enable sanitizers.")
function(target_add_sanitizers target default_on)
  include(AddFlags)
  if (SANITIZE OR ${default_on})
    target_add_flags(${target} "fsanitize=address;fsanitize=undefined" TRUE FALSE)
  endif()
endfunction()
